export const SET_REPO_IN_FAVORITE = 'SET_REPO_IN_FAVORITE';
export const REMOVE_REPO_FROM_FAVORITE = 'REMOVE_REPO_FROM_FAVORITE';
export const SET_REPO_LISTS = "SET_REPO_LISTS";
export const SET_THEME="SET_THEME";